export default [{
        href: "/",
        bg: "assets/img/img_1.png",
        logoImg: "assets/img/user_1.png",
        statImg: "assets/img/stat_img.png",
        time: "23:45",
        score: "23:45",
    },
    {
        href: "/",
        bg: "assets/img/img_2.png",
        logoImg: "assets/img/user_2.png",
        statImg: "assets/img/stat_img.png",
        time: "23:45",
        score: "23:45",
    },
    {
        href: "/",
        bg: "assets/img/img_3.png",
        logoImg: "assets/img/user_3.png",
        statImg: "assets/img/stat_img.png",
        time: "23:45",
        score: "23:45",
    },
    {
        href: "/",
        bg: "assets/img/img_4.png",
        logoImg: "assets/img/user_4.png",
        statImg: "assets/img/stat_img.png",
        time: "23:45",
        score: "23:45",
    },
    {
        href: "/",
        bg: "assets/img/img_5.png",
        logoImg: "assets/img/user_6.png",
        statImg: "assets/img/stat_img.png",
        time: "23:45",
        score: "23:45",
    },
];